# - name: Install VirtualBox using Chocolatey
#   win_chocolatey:
#     name: virtualbox
#     version: '7.1.8'
#     state: present

# - name: Install WSL2
#   win_chocolatey:
#     name: wsl2
#     state: present

# - name: Install Ubuntu 22.04 on WSL
#   win_shell: wsl --install -d Ubuntu-22.04
- name: Install Chocolatey
  win_chocolatey:
    name: chocolatey
    state: present

- name: Install Docker Desktop using Chocolatey
  win_chocolatey:
    name: docker-desktop
    # version: '4.25.2'
    state: present

- name: Create Docker Desktop settings directory
  win_file:
    path: '{{ ansible_env.APPDATA }}\Docker\settings.json'
    state: directory

- name: Configure Docker Desktop settings
  win_copy:
    dest: '{{ ansible_env.APPDATA }}\Docker\settings.json'
    content: |
      {
        "autoStart": true,
        "wslEngineEnabled": true,
        "useWindowsContainers": false
      }
#
# - name: Install Rancher Desktop using Chocolatey
#   win_chocolatey:
#     name: rancher-desktop
#     state: present
#
# - name: Create Rancher Desktop config directory
#   win_file:
#     path: '{{ ansible_env.USERPROFILE }}\.rd'
#     state: directory
#
# - name: Configure Rancher Desktop to use containerd
#   win_copy:
#     dest: '{{ ansible_env.USERPROFILE }}\.rd\rancher-desktop.json'
#     content: |
#       {
#         "containerEngine": {
#           "name": "containerd"
#         }
#       }
#
