experimental_monorepo_root = true

[tools]
azure-cli = "2.78.0"

[env]
MISE_EXPERIMENTAL = "1"

[vars]
do_homelab_pk_ssh_key_name = 'do_homelab'

[tasks.init]
run = [
    'mise tasks run //terraform/deployments/bootstrap:init',
    'mise tasks run //terraform/deployments/common:init',
    'mise tasks run //terraform/deployments/environments/dev:init',
]

[tasks.check]
run = ['mise tasks run //ansible:check']


[tasks.deploy_dev]
run = [
    'mise tasks run //terraform/deployments/environments/dev:apply',
    'mise tasks run //terraform/deployments/environments/dev:get_do_homelab_pk > ~/.ssh/{{vars.do_homelab_pk_ssh_key_name}}',
    'mise tasks run //ansible:deploy_dev',
]

[tasks.destroy_dev]
run = ['mise tasks run //terraform/deployments/environments/dev:destroy']
