version: '3'

includes:
  blog: ./blog
  terraform: ./terraform

vars:
  ENVIRONMENTS:
    - dev
    - prod

tasks:
  _deploy:
    internal: true
    desc: 'Internal template for deploying an environment'
    vars:
      ENV: '{{.ENV}}'
    cmds:
      - task: blog:build:{{.ENV}}
      - task: terraform:deploy:{{.ENV}}

  _destroy:
    internal: true
    desc: 'Internal template for destroying an environment'
    vars:
      ENV: '{{.ENV}}'
    cmds:
      - task: terraform:destroy:{{.ENV}}

  deploy:
    desc: 'Deploy a specific environment (usage: task deploy ENV=dev)'
    cmds:
      - task: _deploy
        vars:
          ENV: '{{.ENV}}'

  destroy:
    desc: 'Destroy a specific environment (usage: task destroy ENV=dev)'
    cmds:
      - task: _destroy
        vars:
          ENV: '{{.ENV}}'

  deploy:all:
    desc: Deploy all environments
    cmds:
      - task: terraform:deploy:global
      - task: deploy ENV=dev
      - task: deploy ENV=prod


