apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-cpu
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-cpu
  template:
    metadata:
      labels:
        app: ollama-cpu
    spec:
      containers:
        - name: ollama-cpu
          image: ollama/ollama:0.34.2
          ports:
            - containerPort: 11434
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 4Gi
          volumeMounts:
            - name: data
              mountPath: /root/.ollama
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ollama-cpu-data
