apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-cpu-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ollama-cpu-local-path
  resources:
    requests:
      storage: 10Gi
