version: '3'
tasks:
  terraform.destroy.dev:
    dir: '{{.TASKFILE_DIR}}/environments/dev'
    cmd: terraform destroy
  terraform.destroy.prod:
    dir: '{{.TASKFILE_DIR}}/environments/prod'
    cmd: terraform destroy
  terraform.destroy.global:
    dir: '{{.TASKFILE_DIR}}/global'
    cmd: terraform destroy
  terraform.plan.dev:
    dir: '{{.TASKFILE_DIR}}/environments/dev'
    cmd: terraform plan
  terraform.plan.prod:
    dir: '{{.TASKFILE_DIR}}/environments/prod'
    cmd: terraform plan
  terraform.plan.global:
    dir: '{{.TASKFILE_DIR}}/global'
    cmd: terraform plan
  terraform.apply.dev:
    dir: '{{.TASKFILE_DIR}}/environments/dev'
    cmd: terraform apply
  terraform.apply.prod:
    dir: '{{.TASKFILE_DIR}}/environments/prod'
    cmd: terraform apply
  terraform.apply.global:
    dir: '{{.TASKFILE_DIR}}/global'
    cmd: terraform apply
  terraform.apply:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - task terraform.apply.global
      - task terraform.apply.dev
      - task terraform.apply.prod
