version: '3'
vars:
  ENVIRONMENT: '{{ .ENVIRONMENT | default "dev" }}'

tasks:
  deploy:
    internal: true
    dir: '{{.TASKFILE_DIR}}/deployments/environments/{{.ENVIRONMENT}}'
    cmd: terraform apply

  destroy:
    internal: true
    dir: '{{.TASKFILE_DIR}}/deployments/environments/{{.ENVIRONMENT}}'
    cmd: terraform destroy

  deploy:dev:
    cmds:
      - task: deploy
        vars:
          ENVIRONMENT: dev

  deploy:prod:
    cmds:
      - task: deploy
        vars:
          ENVIRONMENT: prod

  destroy:dev:
    cmds:
      - task: destroy
        vars:
          ENVIRONMENT: dev

  destroy:prod:
    cmds:
      - task: destroy
        vars:
          ENVIRONMENT: prod

  deploy:global:
    dir: '{{.TASKFILE_DIR}}/deployments/global'
    cmd: terraform apply
