version: '3'
tasks:
  tf.destroy.dev:
    dir: '{{.TASKFILE_DIR}}/environments/dev'
    cmd: terraform destroy
  tf.destroy.prod:
    dir: '{{.TASKFILE_DIR}}/environments/prod'
    cmd: terraform destroy
  tf.destroy.global:
    dir: '{{.TASKFILE_DIR}}/global'
    cmd: terraform destroy
  tf.plan.dev:
    dir: '{{.TASKFILE_DIR}}/environments/dev'
    cmd: terraform plan
  tf.plan.prod:
    dir: '{{.TASKFILE_DIR}}/environments/prod'
    cmd: terraform plan
  tf.plan.global:
    dir: '{{.TASKFILE_DIR}}/global'
    cmd: terraform plan
  tf.apply.dev:
    dir: '{{.TASKFILE_DIR}}/environments/dev'
    cmd: terraform apply
  tf.apply.prod:
    dir: '{{.TASKFILE_DIR}}/environments/prod'
    cmd: terraform apply
  tf.apply.global:
    dir: '{{.TASKFILE_DIR}}/global'
    cmd: terraform apply
  tf.apply:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - task tf.apply.global
      - task tf.apply.dev
      - task tf.apply.prod
