# kubeadm-config.yaml
# - This section defines the basic cluster setup parameters
# - It specifies that Kubernetes version 1.33.1 should be used when initializing the cluster
# - This configuration is used by kubeadm when bootstrapping the control plane components
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
kubernetesVersion: v1.33.1
---
# - This section configures the kubelet (the primary node agent that runs on each node)
# - The key setting here is `cgroupDriver: systemd`, which tells kubelet to use systemd as the cgroup driver
# - This is important for container runtime integration and resource management
# - Using systemd as the cgroup driver is the recommended approach when using systemd as your init system
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
