all:
  hosts:
    nuc_host:
      ansible_host: "{{ lookup('ansible.builtin.env', 'NUC_IP') | default('127.0.0.1') }}"
      ansible_user: "{{ lookup('ansible.builtin.env', 'NUC_USER') }}"
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
      ansible_password: "{{ lookup('ansible.builtin.env', 'NUC_PASSWORD') }}"
      ansible_winrm_server_cert_validation: ignore
      ansible_port: 5985
      ansible_winrm_scheme: http
      ansible_winrm_operation_timeout_sec: 120
      ansible_winrm_read_timeout_sec: 150
      ansible_winrm_message_encryption: auto

    control_plane:
      ansible_host: "{{ lookup('ansible.builtin.env', 'ANSIBLE_HOST') | default('127.0.0.1') }}"
      ansible_user: "{{ lookup('ansible.builtin.env', 'ANSIBLE_USER') | default('admin') }}"
      ansible_ssh_private_key_file: "{{ lookup('ansible.builtin.env', 'ANSIBLE_SSH_KEY') | default('~/.ssh/id_ed25519') }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
