- name: Install kubernetes
  hosts: control_plane
  gather_facts: true
  tasks:
    - name: Ping test
      ping:
    - name: Get host information
      debug:
        msg: "Successfully connected to {{ ansible_hostname }} running {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Update apt package cache
      become: true
      apt:
        update_cache: yes

    - name: Install required packages for Docker repository
      become: true
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create keyrings directory
      become: true
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      become: true
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

    - name: Set correct permissions for Docker GPG key
      become: true
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: 'a+r'

    - name: Set up Docker repository
      become: true
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt package cache
      become: true
      apt:
        update_cache: yes

    - name: Install Docker packages
      become: true
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Add user to docker group
      become: true
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable Docker service
      become: true
      systemd:
        name: docker
        state: started
        enabled: yes
