- name: Install kubernetes
  hosts: control_plane
  gather_facts: true
  tasks:
    - name: Ping test
      ping:
    - name: Get host information
      debug:
        msg: "Successfully connected to {{ ansible_hostname }} running {{ ansible_distribution }} {{ ansible_distribution_version }}"
    - name: Update apt package cache
      become: true
      apt:
        update_cache: yes
    - name: Install required packages for Docker repository
      become: true
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
    - name: Create Docker keyring directory
      become: true
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Download Docker's GPG key
      become: true
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
    - name: Add Docker repository
      become: true
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: yes
    - name: Install Docker packages
      become: true
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
    - name: Add user to docker group
      become: true
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    - name: Enable Docker service
      become: true
      systemd:
        name: docker
        state: started
        enabled: yes
