- name: Setup NUC
  hosts: nuc_host
  gather_facts: true
  tasks:
    - name: install virtualbox
      ansible.builtin.import_tasks: tasks/install-virtualbox.yaml
      tags:
        - virtualbox

    - name: setup kubernetes control plane
      ansible.builtin.import_tasks: tasks/manage-virtualbox-vms.yaml
      tags:
        - k8s-cp-vm

# - name: Install kubernetes
#   hosts: control_plane
#   gather_facts: true
#   tasks:
#     - name: Import Docker installation tasks
#       ansible.builtin.import_tasks: tasks/install-docker.yml
#       tags:
#         - docker
#
#     - name: Import Kubernetes installation tasks
#       ansible.builtin.import_tasks: tasks/install-kubernetes.yml
#       tags:
#         - kubernetes
