- name: Create Jellyfin directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /srv/jellyfin
    - /srv/jellyfin/config
    - /srv/jellyfin/media/movies
  become: true
