services:
  ollama:
    image: ollama/ollama:0.15.1
    container_name: ollama
    restart: unless-stopped
    networks:
      - homelab
    ports:
      - "11434:11434"
    volumes:
      - /srv/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  shadowrun-rag:
    image: ${REGISTRY_HOST}/homelab/shadowrun-rag:latest
    user: "${PUID}:${PGID}"
    container_name: shadowrun-rag
    restart: unless-stopped
    environment:
      - DATA_PATH=/data
      - EMBEDDING_BATCH_SIZE=100
      - EMBEDDING_MODEL=mxbai-embed-large
      - LLM_MODEL=llama3.1:8b
      - LOG_LEVEL=INFO
      - OLLAMA_HOST=http://ollama:11434
      - PYTORCH_ALLOC_CONF=expandable_segments:True
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - TOP_K=7
    volumes:
      - /srv/shadowrun-rag/pdfs:/data/pdfs:ro
      - /srv/shadowrun-rag/extracted:/data/extracted
      - /srv/shadowrun-rag/chroma_db:/data/chroma_db
      - /srv/shadowrun-rag/model_cache:/${USER}/.cache
    networks:
      - homelab
    depends_on:
      - ollama
    # Override command to keep running for manual exec
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  filebrowser:
    image: hurlenko/filebrowser:v2.63.2
    user: "${PUID}:${PGID}"
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /srv/shadowrun-rag/pdfs:/data/shadowrun-rag
      # - /srv/filebrowser/database.db:/database.db
    networks:
      - homelab

networks:
  homelab:
    external: true
