version: '3'

vars:
  ENVIRONMENT: '{{ .ENVIRONMENT | default "dev" }}'

tasks:
  build:
    desc: Build the Hugo site (use ENVIRONMENT=prod for production build)
    internal: true
    dir: '{{.TASKFILE_DIR}}/app'
    cmds:
      - hugo --environment {{.ENVIRONMENT}}

  build:dev:
    desc: Build the Hugo site for development
    cmds:
      - task: build
        vars:
          ENVIRONMENT: dev

  build:prod:
    desc: Build the Hugo site for production
    cmds:
      - task: build
        vars:
          ENVIRONMENT: prod
