apiVersion: apps/v1
kind: Deployment
metadata:
  name: starwars-armada
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starwars-armada
  template:
    metadata:
      labels:
        app: starwars-armada
    spec:
      nodeSelector:
        homelab-role: nuc
      containers:
        - name: starwars-armada
          image: registry.home.gaborzeller.com/homelab/starwars-armada:latest
          env:
            - name: OLLAMA_HOST
              value: http://ollama-cpu.default.svc.cluster.local:11434
            - name: EMBEDDING_OLLAMA_HOST
              value: http://10.83.16.99:11434
            - name: CHROMA_DB_PATH
              value: /build/chroma_db
            - name: EMBEDDING_BATCH_SIZE
              value: "10"
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: 256Mi
            limits:
              cpu: "500m"
              memory: 512Mi
          volumeMounts:
            - name: raw-data
              mountPath: /data
            - name: build-data
              mountPath: /build
      volumes:
        - name: raw-data
          hostPath:
            path: /srv/starwars-armada
            type: Directory
        - name: build-data
          persistentVolumeClaim:
            claimName: starwars-armada-build
