apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: starwars-armada-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: starwars-armada-local-path
  resources:
    requests:
      storage: 5Gi
