languageCode: en-us
title: Gabor Zeller
theme: ["PaperMod"]
params:
  contact:
    email: contact@gaborzeller.com
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
