apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homelab-postgres
  namespace: default
spec:
  instances: 1
  affinity:
    nodeSelector:
      homelab-role: nuc
  storage:
    size: 10Gi
    storageClass: postgres-local-path
  managed:
    roles:
      - name: ebay_scraper
        ensure: present
        login: true
        passwordSecret:
          name: ebay-scraper-password
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: homelab-postgres-lb
            spec:
              type: LoadBalancer
