apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storageclass.yaml
  - cluster.yaml

configMapGenerator:
  - name: local-path-config
    namespace: kube-system
    files:
      - config.json=local-path-config.json
    options:
      disableNameSuffixHash: true
