- Homelab:
    - Technitium:
        icon: technitium.svg
        href: https://technitium.home.gaborzeller.com
        description: DNS + ad blocking
        widget:
          type: technitium
          url: http://technitium-external.default.svc.cluster.local:5380
          key: "{{HOMEPAGE_VAR_TECHNITIUM_KEY}}"
    - Prometheus:
        icon: prometheus.svg
        href: https://prometheus.home.gaborzeller.com
        description: Prometheus
        widget:
          type: prometheus
          url: http://prometheus.default.svc.cluster.local:9090
    - Grafana:
        icon: grafana.svg
        href: https://grafana.home.gaborzeller.com
        description: Grafana
        widget:
          type: grafana
          url: http://grafana.default.svc.cluster.local:3000
          username: admin
          password: "{{HOMEPAGE_VAR_GRAFANA_ADMIN_PASSWORD}}"
    - Jellyfin:
        icon: jellyfin.svg
        href: https://jellyfin.home.gaborzeller.com
        description: Jellyfin
        widget:
          type: jellyfin
          url: http://jellyfin.default.svc.cluster.local:8096
          key: "{{HOMEPAGE_VAR_JELLYFIN_KEY}}"
          enableBlocks: true
          version: 2
          enableUser: true
    - Registry:
        href: https://registry-ui.home.gaborzeller.com
        description: Image registry
