- Homelab:
    - Technitium:
        icon: technitium.svg
        href: https://technitium.home.gaborzeller.com
        description: DNS + ad blocking
    - Prometheus:
        icon: prometheus.svg
        href: https://prometheus.home.gaborzeller.com
        description: Prometheus
        widget:
          type: prometheus
          url: http://prometheus.default.svc.cluster.local:9090
    - Grafana:
        icon: grafana.svg
        href: https://grafana.home.gaborzeller.com
        description: Grafana
    - Jellyfin:
        icon: jellyfin.svg
        href: https://jellyfin.home.gaborzeller.com
        description: Jellyfin
        widget:
          type: jellyfin
          url: http://jellyfin.default.svc.cluster.local:8096
          key: "{{HOMEPAGE_VAR_JELLYFIN_KEY}}"
          enableBlocks: true
