apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    env:
      - name: CF_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: apiToken
    certificatesResolvers:
      cloudflare:
        acme:
          email: gabriel.d.celery@gmail.com
          storage: /data/acme.json
          dnsChallenge:
            provider: cloudflare
    persistence:
      enabled: true
      path: /data
    deployment:
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
          volumeMounts:
            - name: data
              mountPath: /data
